---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-chronicler-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: po-chronicler
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: po-chronicler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: po-chronicler
    spec:
      serviceAccountName: chronicler-migration-waiter
      initContainers:
        - name: wait-for-migration
          image: groundnuty/k8s-wait-for:v2.0
          args:
            - "job"
            - "po-chronicler-migrate-job-{{ .Values.image.tag | default .Chart.AppVersion | replace "." "-" }}"
      containers:
        - name: po-chronicler
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          args:
            - "--serve"
          env:
            {{- include "database.config" . | nindent 12 }}

            # OpenTelemetry Collector Configuration
            - name: Otlp__Enabled
              value: {{ .Values.otlp.enabled | quote }}
            - name: Otlp__Endpoint
              value: {{ .Values.otlp.endpoint }}

            # Chronicler Configuration
            {{- if .Values.config.networkConfigurationFile }}
            - name: NetworkConfigurationUri
              value: /etc/config/networkConfiguration.json
            {{- else if .Values.config.networkConfigurationUri }}
            - name: NetworkConfigurationUri
              value: {{ .Values.config.networkConfigurationUri }}
            {{- else }}
              {{ fail "No network configuration provided" }}
            {{- end }}

            - name: chronicler__JobInterval
              value: {{ .Values.config.jobInterval }}

            - name: chronicler__SigningKey
              value: /etc/secret/signing-key

            {{- range $i, $area := .Values.config.gridAreas }}
            - name: chronicler__GridAreas__{{ $i }}
              value: {{ $area }}
            {{- end }}
          volumeMounts:
            - name: signing-key-volume
              mountPath: /etc/secret
              subPath: signing-key
            {{- if .Values.config.networkConfigurationFile }}
            - name: config-volume
              mountPath: /etc/config
              subPath: networkConfiguration.json
            {{- end }}


      volumes:
        - name: signing-key-volume
          secret:
            secretName: {{ .Values.config.signingKeySecret.name }}
            items:
              - key: {{ .Values.config.signingKeySecret.key }}
                path: signing-key
        {{- if .Values.config.networkConfigurationFile }}
        - name: config-volume
          configMap:
            name: po-chronicler-deployment-config
            items:
              - key: networkConfiguration.json
                path: networkConfiguration.json
        {{- end }}
