---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-chronicler-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: po-chronicler
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: po-chronicler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: po-chronicler
    spec:
      serviceAccountName: chronicler-migration-waiter
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-migration
          image: bitnami/kubectl:1.30.4
          resources:
            requests:
              cpu: 0.1
            limits:
              memory: 50Mi
          command:
            - /bin/sh
            - -c
            - |
              kubectl wait --for=condition=complete job/${JOB_NAME} --timeout=300s -n {{ .Release.Namespace }}
          env:
            - name: JOB_NAME
              value: po-chronicler-migrate-job-{{ .Values.image.tag | default .Chart.AppVersion | replace "." "-" }}
          volumeMounts:
            - name: service-account-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      containers:
        - name: po-chronicler
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          {{ include "limits" . | nindent 10 }}
          args:
            - "--serve"
          env:
            {{- include "database.config" . | nindent 12 }}

            # OpenTelemetry Collector Configuration
            - name: Otlp__Enabled
              value: {{ .Values.otlp.enabled | quote }}
            {{- if .Values.otlp.enabled }}
            - name: Otlp__Endpoint
              value: {{ required "otel.endpoint is required when enabled" .Values.otlp.endpoint | quote }}
            {{- end }}

            # Chronicler Configuration
            {{- if .Values.config.networkConfigurationFile }}
            - name: network__ConfigurationUri
              value: file:///etc/config/networkConfiguration.json
            {{- else if .Values.config.networkConfigurationUri }}
            - name: network__ConfigurationUri
              value: {{ .Values.config.networkConfigurationUri }}
            {{- else }}
              {{ fail "No network configuration provided" }}
            {{- end }}

            - name: chronicler__JobInterval
              value: {{ .Values.config.jobInterval }}

            - name: chronicler__SigningKeyFilename
              value: &signingKeyFilename /etc/secret/signing-key

            {{- range $i, $area := .Values.config.gridAreas }}
            - name: chronicler__GridAreas__{{ $i }}
              value: {{ $area }}
            {{- end }}
          volumeMounts:
            - name: service-account-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: &signingKeyVolumeName signing-key-volume
              mountPath: *signingKeyFilename
              subPath: &signingKeyVolumePath signing-key
            {{- if .Values.config.networkConfigurationFile }}
            - name: &networkConfigVolumeName config-volume
              mountPath: /etc/config/networkConfiguration.json
              subPath:  &networkConfigSubPath networkConfiguration.json
            {{- end }}
      volumes:
        - name: service-account-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: ca.crt
        - name: *signingKeyVolumeName
          secret:
            secretName: {{ .Values.config.signingKeySecret.name }}
            items:
              - key: {{ .Values.config.signingKeySecret.key }}
                path: *signingKeyVolumePath
        {{- if .Values.config.networkConfigurationFile }}
        - name: *networkConfigVolumeName
          configMap:
            name: po-chronicler-deployment-config
            items:
              - key: *networkConfigSubPath
                path: *networkConfigSubPath
        {{- end }}
