---
apiVersion: v1
kind: Service
metadata:
  name: po-chronicler
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: po-chronicler
  ports:
    - name: rest
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: 5000
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: 5001
