name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c
    with:
      imagename: ghcr.io/project-origin/chronicler
      version: test
      context: .
      dockerfile: Chronicler.Dockerfile
      push: false
