name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c

  publish-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c
    with:
      imagename: ghcr.io/project-origin/chronicler
      version: ${{ needs.define-version.outputs.version }}
      context: .
      dockerfile: Chronicler.Dockerfile
      push: true

  publish-chart:
    needs:
      - define-version
      - publish-container
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@c34915280e5eff902ce618f2e2d3d35ad7b9a15c
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: chart
      helm_registry_repository: project-origin/helm-registry
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
